#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace One.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Paradise")]
	public partial class ParadiseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertFACTURA(FACTURA instance);
    partial void UpdateFACTURA(FACTURA instance);
    partial void DeleteFACTURA(FACTURA instance);
    partial void InsertFACTURA1(FACTURA1 instance);
    partial void UpdateFACTURA1(FACTURA1 instance);
    partial void DeleteFACTURA1(FACTURA1 instance);
    partial void InsertFACTURALINIMPUESTO(FACTURALINIMPUESTO instance);
    partial void UpdateFACTURALINIMPUESTO(FACTURALINIMPUESTO instance);
    partial void DeleteFACTURALINIMPUESTO(FACTURALINIMPUESTO instance);
    #endregion
		
		public ParadiseDataContext() : 
				base(global::One.Data.Properties.Settings.Default.ParadiseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ParadiseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ParadiseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ParadiseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ParadiseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FACTURA> FACTURA
		{
			get
			{
				return this.GetTable<FACTURA>();
			}
		}
		
		public System.Data.Linq.Table<FACTURA1> FACTURA1
		{
			get
			{
				return this.GetTable<FACTURA1>();
			}
		}
		
		public System.Data.Linq.Table<FACTURALINIMPUESTO> FACTURALINIMPUESTO
		{
			get
			{
				return this.GetTable<FACTURALINIMPUESTO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FACTURA")]
	public partial class FACTURA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FacId;
		
		private System.Nullable<int> _FacDocNum;
		
		private System.Nullable<System.DateTime> _FacFec;
		
		private System.Nullable<int> _FacCliId;
		
		private System.Nullable<short> _FacConVen;
		
		private System.Nullable<short> _FacRedondeo;
		
		private string _FacObs;
		
		private string _UsuId;
		
		private System.Nullable<short> _FacContador;
		
		private System.Nullable<short> _FacConReal;
		
		private System.Nullable<decimal> _FacTotPto;
		
		private System.Nullable<System.DateTime> _FacFecFac;
		
		private string _FacHorFac;
		
		private System.Nullable<short> _CajaId;
		
		private System.Nullable<char> _FacTipo;
		
		private System.Nullable<char> _FacConTip;
		
		private System.Nullable<char> _FacAnulada;
		
		private System.Nullable<char> _FacCerrada;
		
		private System.Nullable<int> _FacCierre;
		
		private System.Nullable<char> _FacTipPag;
		
		private System.Nullable<decimal> _FacEfectivo;
		
		private System.Nullable<decimal> _FacCambio;
		
		private System.Nullable<int> _FacZCierre;
		
		private System.Nullable<char> _FacSerie;
		
		private System.Nullable<int> _DetCobId;
		
		private System.Nullable<short> _FacMoneda;
		
		private System.Nullable<System.DateTime> _FacFecha;
		
		private string _FacPaxNom;
		
		private System.Nullable<decimal> _FacPaxRuc;
		
		private string _FacPaxDir;
		
		private System.Nullable<short> _FacPaxHab;
		
		private System.Nullable<int> _FacPaxRes;
		
		private System.Nullable<System.DateTime> _FacPaxFEnt;
		
		private string _FacPaxHEnt;
		
		private System.Nullable<System.DateTime> _FacPaxFSal;
		
		private string _FacPaxHSal;
		
		private System.Nullable<System.DateTime> _FacFecAnul;
		
		private string _FacHorAnul;
		
		private string _FacUsuAnul;
		
		private string _FacMaqAnul;
		
		private System.Nullable<decimal> _FacTotHosp;
		
		private System.Nullable<decimal> _FacTotExtras;
		
		private System.Nullable<decimal> _FacTotDescu;
		
		private System.Nullable<decimal> _FacTotImpu;
		
		private System.Nullable<decimal> _FacTotGen;
		
		private System.Nullable<decimal> _FacSenia;
		
		private string _FacSucId;
		
		private System.Nullable<int> _FacJuntoConTicket;
		
		private System.Nullable<int> _FacAsientoInterno;
		
		private System.Nullable<decimal> _FacImpRedondeo;
		
		private System.Nullable<decimal> _FacDescuento;
		
		private System.Nullable<char> _FacTipoContribuyente;
		
		private string _EveCod;
		
		private System.Nullable<short> _FacImpresora;
		
		private System.Nullable<int> _FacUtilSaldoPes;
		
		private System.Nullable<int> _FacUtilSaldoDol;
		
		private System.Nullable<int> _FacCierreTesoreria;
		
		private string _FacNCMotivo;
		
		private string _FacNCUsuId;
		
		private System.Nullable<char> _FacNCAccion;
		
		private System.Nullable<decimal> _FacNCDineroDevuelto;
		
		private System.Nullable<int> _FacCierreMensual;
		
		private System.Nullable<short> _FacDtoHospedaje;
		
		private System.Nullable<short> _FacDtoExtras;
		
		private string _FacRif;
		
		private string _FacPapelNum;
		
		private string _FacCco;
		
		private string _FacFacturaAfectada;
		
		private System.Nullable<int> _FacIdAfectada;
		
		private System.Nullable<int> _FacZCierreIntegrada;
		
		private System.Nullable<int> _FacZCierreMensual;
		
		private System.Nullable<decimal> _FacSeniaUtilizada;
		
		private string _FacCodigoError;
		
		private System.Nullable<System.DateTime> _FacFechaHoraParaAnul;
		
		private string _FacCFEFirma;
		
		private System.Nullable<short> _FacCFETipo;
		
		private string _FacCFESerie;
		
		private System.Nullable<int> _FacCFENumero;
		
		private System.Nullable<System.DateTime> _FacCFEFechaEmision;
		
		private string _FacCFEReceptorCiudad;
		
		private string _FacCFEReceptorDepartamento;
		
		private System.Nullable<short> _FacCFEReceptorTipoDocIdentidad;
		
		private string _FacCFEReceptorNroDocIdentidad;
		
		private string _FacCFECae;
		
		private System.Nullable<System.DateTime> _FacCFECaeVen;
		
		private System.Nullable<char> _FacAnuladaElectronica;
		
		private string _FacCFEReceptorPaisDGI;
		
		private string _FacPaisCod;
		
		private System.Nullable<char> _FacContingencia;
		
		private string _FacContingenciaFacCFECae;
		
		private string _FacContingenciaFacCFESerie;
		
		private System.Nullable<System.DateTime> _FacContingenciaFacCFECaeVen;
		
		private System.Nullable<int> _FacContingenciaCaeDesde;
		
		private System.Nullable<int> _FacContingenciaCaeHasta;
		
		private System.Nullable<int> _FacContingeciaCaeNumero;
		
		private System.Nullable<int> _FacSecuencialShoppping;
		
		private System.Nullable<short> _FacCliSucId;
		
		private System.Nullable<char> _FacCliSucurLey15921;
		
		private System.Nullable<short> _FacLisId;
		
		private System.Nullable<int> _FacCabExportacionId;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFacIdChanging(int value);
    partial void OnFacIdChanged();
    partial void OnFacDocNumChanging(System.Nullable<int> value);
    partial void OnFacDocNumChanged();
    partial void OnFacFecChanging(System.Nullable<System.DateTime> value);
    partial void OnFacFecChanged();
    partial void OnFacCliIdChanging(System.Nullable<int> value);
    partial void OnFacCliIdChanged();
    partial void OnFacConVenChanging(System.Nullable<short> value);
    partial void OnFacConVenChanged();
    partial void OnFacRedondeoChanging(System.Nullable<short> value);
    partial void OnFacRedondeoChanged();
    partial void OnFacObsChanging(string value);
    partial void OnFacObsChanged();
    partial void OnUsuIdChanging(string value);
    partial void OnUsuIdChanged();
    partial void OnFacContadorChanging(System.Nullable<short> value);
    partial void OnFacContadorChanged();
    partial void OnFacConRealChanging(System.Nullable<short> value);
    partial void OnFacConRealChanged();
    partial void OnFacTotPtoChanging(System.Nullable<decimal> value);
    partial void OnFacTotPtoChanged();
    partial void OnFacFecFacChanging(System.Nullable<System.DateTime> value);
    partial void OnFacFecFacChanged();
    partial void OnFacHorFacChanging(string value);
    partial void OnFacHorFacChanged();
    partial void OnCajaIdChanging(System.Nullable<short> value);
    partial void OnCajaIdChanged();
    partial void OnFacTipoChanging(System.Nullable<char> value);
    partial void OnFacTipoChanged();
    partial void OnFacConTipChanging(System.Nullable<char> value);
    partial void OnFacConTipChanged();
    partial void OnFacAnuladaChanging(System.Nullable<char> value);
    partial void OnFacAnuladaChanged();
    partial void OnFacCerradaChanging(System.Nullable<char> value);
    partial void OnFacCerradaChanged();
    partial void OnFacCierreChanging(System.Nullable<int> value);
    partial void OnFacCierreChanged();
    partial void OnFacTipPagChanging(System.Nullable<char> value);
    partial void OnFacTipPagChanged();
    partial void OnFacEfectivoChanging(System.Nullable<decimal> value);
    partial void OnFacEfectivoChanged();
    partial void OnFacCambioChanging(System.Nullable<decimal> value);
    partial void OnFacCambioChanged();
    partial void OnFacZCierreChanging(System.Nullable<int> value);
    partial void OnFacZCierreChanged();
    partial void OnFacSerieChanging(System.Nullable<char> value);
    partial void OnFacSerieChanged();
    partial void OnDetCobIdChanging(System.Nullable<int> value);
    partial void OnDetCobIdChanged();
    partial void OnFacMonedaChanging(System.Nullable<short> value);
    partial void OnFacMonedaChanged();
    partial void OnFacFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFacFechaChanged();
    partial void OnFacPaxNomChanging(string value);
    partial void OnFacPaxNomChanged();
    partial void OnFacPaxRucChanging(System.Nullable<decimal> value);
    partial void OnFacPaxRucChanged();
    partial void OnFacPaxDirChanging(string value);
    partial void OnFacPaxDirChanged();
    partial void OnFacPaxHabChanging(System.Nullable<short> value);
    partial void OnFacPaxHabChanged();
    partial void OnFacPaxResChanging(System.Nullable<int> value);
    partial void OnFacPaxResChanged();
    partial void OnFacPaxFEntChanging(System.Nullable<System.DateTime> value);
    partial void OnFacPaxFEntChanged();
    partial void OnFacPaxHEntChanging(string value);
    partial void OnFacPaxHEntChanged();
    partial void OnFacPaxFSalChanging(System.Nullable<System.DateTime> value);
    partial void OnFacPaxFSalChanged();
    partial void OnFacPaxHSalChanging(string value);
    partial void OnFacPaxHSalChanged();
    partial void OnFacFecAnulChanging(System.Nullable<System.DateTime> value);
    partial void OnFacFecAnulChanged();
    partial void OnFacHorAnulChanging(string value);
    partial void OnFacHorAnulChanged();
    partial void OnFacUsuAnulChanging(string value);
    partial void OnFacUsuAnulChanged();
    partial void OnFacMaqAnulChanging(string value);
    partial void OnFacMaqAnulChanged();
    partial void OnFacTotHospChanging(System.Nullable<decimal> value);
    partial void OnFacTotHospChanged();
    partial void OnFacTotExtrasChanging(System.Nullable<decimal> value);
    partial void OnFacTotExtrasChanged();
    partial void OnFacTotDescuChanging(System.Nullable<decimal> value);
    partial void OnFacTotDescuChanged();
    partial void OnFacTotImpuChanging(System.Nullable<decimal> value);
    partial void OnFacTotImpuChanged();
    partial void OnFacTotGenChanging(System.Nullable<decimal> value);
    partial void OnFacTotGenChanged();
    partial void OnFacSeniaChanging(System.Nullable<decimal> value);
    partial void OnFacSeniaChanged();
    partial void OnFacSucIdChanging(string value);
    partial void OnFacSucIdChanged();
    partial void OnFacJuntoConTicketChanging(System.Nullable<int> value);
    partial void OnFacJuntoConTicketChanged();
    partial void OnFacAsientoInternoChanging(System.Nullable<int> value);
    partial void OnFacAsientoInternoChanged();
    partial void OnFacImpRedondeoChanging(System.Nullable<decimal> value);
    partial void OnFacImpRedondeoChanged();
    partial void OnFacDescuentoChanging(System.Nullable<decimal> value);
    partial void OnFacDescuentoChanged();
    partial void OnFacTipoContribuyenteChanging(System.Nullable<char> value);
    partial void OnFacTipoContribuyenteChanged();
    partial void OnEveCodChanging(string value);
    partial void OnEveCodChanged();
    partial void OnFacImpresoraChanging(System.Nullable<short> value);
    partial void OnFacImpresoraChanged();
    partial void OnFacUtilSaldoPesChanging(System.Nullable<int> value);
    partial void OnFacUtilSaldoPesChanged();
    partial void OnFacUtilSaldoDolChanging(System.Nullable<int> value);
    partial void OnFacUtilSaldoDolChanged();
    partial void OnFacCierreTesoreriaChanging(System.Nullable<int> value);
    partial void OnFacCierreTesoreriaChanged();
    partial void OnFacNCMotivoChanging(string value);
    partial void OnFacNCMotivoChanged();
    partial void OnFacNCUsuIdChanging(string value);
    partial void OnFacNCUsuIdChanged();
    partial void OnFacNCAccionChanging(System.Nullable<char> value);
    partial void OnFacNCAccionChanged();
    partial void OnFacNCDineroDevueltoChanging(System.Nullable<decimal> value);
    partial void OnFacNCDineroDevueltoChanged();
    partial void OnFacCierreMensualChanging(System.Nullable<int> value);
    partial void OnFacCierreMensualChanged();
    partial void OnFacDtoHospedajeChanging(System.Nullable<short> value);
    partial void OnFacDtoHospedajeChanged();
    partial void OnFacDtoExtrasChanging(System.Nullable<short> value);
    partial void OnFacDtoExtrasChanged();
    partial void OnFacRifChanging(string value);
    partial void OnFacRifChanged();
    partial void OnFacPapelNumChanging(string value);
    partial void OnFacPapelNumChanged();
    partial void OnFacCcoChanging(string value);
    partial void OnFacCcoChanged();
    partial void OnFacFacturaAfectadaChanging(string value);
    partial void OnFacFacturaAfectadaChanged();
    partial void OnFacIdAfectadaChanging(System.Nullable<int> value);
    partial void OnFacIdAfectadaChanged();
    partial void OnFacZCierreIntegradaChanging(System.Nullable<int> value);
    partial void OnFacZCierreIntegradaChanged();
    partial void OnFacZCierreMensualChanging(System.Nullable<int> value);
    partial void OnFacZCierreMensualChanged();
    partial void OnFacSeniaUtilizadaChanging(System.Nullable<decimal> value);
    partial void OnFacSeniaUtilizadaChanged();
    partial void OnFacCodigoErrorChanging(string value);
    partial void OnFacCodigoErrorChanged();
    partial void OnFacFechaHoraParaAnulChanging(System.Nullable<System.DateTime> value);
    partial void OnFacFechaHoraParaAnulChanged();
    partial void OnFacCFEFirmaChanging(string value);
    partial void OnFacCFEFirmaChanged();
    partial void OnFacCFETipoChanging(System.Nullable<short> value);
    partial void OnFacCFETipoChanged();
    partial void OnFacCFESerieChanging(string value);
    partial void OnFacCFESerieChanged();
    partial void OnFacCFENumeroChanging(System.Nullable<int> value);
    partial void OnFacCFENumeroChanged();
    partial void OnFacCFEFechaEmisionChanging(System.Nullable<System.DateTime> value);
    partial void OnFacCFEFechaEmisionChanged();
    partial void OnFacCFEReceptorCiudadChanging(string value);
    partial void OnFacCFEReceptorCiudadChanged();
    partial void OnFacCFEReceptorDepartamentoChanging(string value);
    partial void OnFacCFEReceptorDepartamentoChanged();
    partial void OnFacCFEReceptorTipoDocIdentidadChanging(System.Nullable<short> value);
    partial void OnFacCFEReceptorTipoDocIdentidadChanged();
    partial void OnFacCFEReceptorNroDocIdentidadChanging(string value);
    partial void OnFacCFEReceptorNroDocIdentidadChanged();
    partial void OnFacCFECaeChanging(string value);
    partial void OnFacCFECaeChanged();
    partial void OnFacCFECaeVenChanging(System.Nullable<System.DateTime> value);
    partial void OnFacCFECaeVenChanged();
    partial void OnFacAnuladaElectronicaChanging(System.Nullable<char> value);
    partial void OnFacAnuladaElectronicaChanged();
    partial void OnFacCFEReceptorPaisDGIChanging(string value);
    partial void OnFacCFEReceptorPaisDGIChanged();
    partial void OnFacPaisCodChanging(string value);
    partial void OnFacPaisCodChanged();
    partial void OnFacContingenciaChanging(System.Nullable<char> value);
    partial void OnFacContingenciaChanged();
    partial void OnFacContingenciaFacCFECaeChanging(string value);
    partial void OnFacContingenciaFacCFECaeChanged();
    partial void OnFacContingenciaFacCFESerieChanging(string value);
    partial void OnFacContingenciaFacCFESerieChanged();
    partial void OnFacContingenciaFacCFECaeVenChanging(System.Nullable<System.DateTime> value);
    partial void OnFacContingenciaFacCFECaeVenChanged();
    partial void OnFacContingenciaCaeDesdeChanging(System.Nullable<int> value);
    partial void OnFacContingenciaCaeDesdeChanged();
    partial void OnFacContingenciaCaeHastaChanging(System.Nullable<int> value);
    partial void OnFacContingenciaCaeHastaChanged();
    partial void OnFacContingeciaCaeNumeroChanging(System.Nullable<int> value);
    partial void OnFacContingeciaCaeNumeroChanged();
    partial void OnFacSecuencialShopppingChanging(System.Nullable<int> value);
    partial void OnFacSecuencialShopppingChanged();
    partial void OnFacCliSucIdChanging(System.Nullable<short> value);
    partial void OnFacCliSucIdChanged();
    partial void OnFacCliSucurLey15921Changing(System.Nullable<char> value);
    partial void OnFacCliSucurLey15921Changed();
    partial void OnFacLisIdChanging(System.Nullable<short> value);
    partial void OnFacLisIdChanged();
    partial void OnFacCabExportacionIdChanging(System.Nullable<int> value);
    partial void OnFacCabExportacionIdChanged();
    #endregion
		
		public FACTURA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FacId
		{
			get
			{
				return this._FacId;
			}
			set
			{
				if ((this._FacId != value))
				{
					this.OnFacIdChanging(value);
					this.SendPropertyChanging();
					this._FacId = value;
					this.SendPropertyChanged("FacId");
					this.OnFacIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacDocNum", DbType="Int")]
		public System.Nullable<int> FacDocNum
		{
			get
			{
				return this._FacDocNum;
			}
			set
			{
				if ((this._FacDocNum != value))
				{
					this.OnFacDocNumChanging(value);
					this.SendPropertyChanging();
					this._FacDocNum = value;
					this.SendPropertyChanged("FacDocNum");
					this.OnFacDocNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacFec", DbType="DateTime")]
		public System.Nullable<System.DateTime> FacFec
		{
			get
			{
				return this._FacFec;
			}
			set
			{
				if ((this._FacFec != value))
				{
					this.OnFacFecChanging(value);
					this.SendPropertyChanging();
					this._FacFec = value;
					this.SendPropertyChanged("FacFec");
					this.OnFacFecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCliId", DbType="Int")]
		public System.Nullable<int> FacCliId
		{
			get
			{
				return this._FacCliId;
			}
			set
			{
				if ((this._FacCliId != value))
				{
					this.OnFacCliIdChanging(value);
					this.SendPropertyChanging();
					this._FacCliId = value;
					this.SendPropertyChanged("FacCliId");
					this.OnFacCliIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacConVen", DbType="SmallInt")]
		public System.Nullable<short> FacConVen
		{
			get
			{
				return this._FacConVen;
			}
			set
			{
				if ((this._FacConVen != value))
				{
					this.OnFacConVenChanging(value);
					this.SendPropertyChanging();
					this._FacConVen = value;
					this.SendPropertyChanged("FacConVen");
					this.OnFacConVenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacRedondeo", DbType="SmallInt")]
		public System.Nullable<short> FacRedondeo
		{
			get
			{
				return this._FacRedondeo;
			}
			set
			{
				if ((this._FacRedondeo != value))
				{
					this.OnFacRedondeoChanging(value);
					this.SendPropertyChanging();
					this._FacRedondeo = value;
					this.SendPropertyChanged("FacRedondeo");
					this.OnFacRedondeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacObs", DbType="Char(100)")]
		public string FacObs
		{
			get
			{
				return this._FacObs;
			}
			set
			{
				if ((this._FacObs != value))
				{
					this.OnFacObsChanging(value);
					this.SendPropertyChanging();
					this._FacObs = value;
					this.SendPropertyChanged("FacObs");
					this.OnFacObsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuId", DbType="Char(10)")]
		public string UsuId
		{
			get
			{
				return this._UsuId;
			}
			set
			{
				if ((this._UsuId != value))
				{
					this.OnUsuIdChanging(value);
					this.SendPropertyChanging();
					this._UsuId = value;
					this.SendPropertyChanged("UsuId");
					this.OnUsuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacContador", DbType="SmallInt")]
		public System.Nullable<short> FacContador
		{
			get
			{
				return this._FacContador;
			}
			set
			{
				if ((this._FacContador != value))
				{
					this.OnFacContadorChanging(value);
					this.SendPropertyChanging();
					this._FacContador = value;
					this.SendPropertyChanged("FacContador");
					this.OnFacContadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacConReal", DbType="SmallInt")]
		public System.Nullable<short> FacConReal
		{
			get
			{
				return this._FacConReal;
			}
			set
			{
				if ((this._FacConReal != value))
				{
					this.OnFacConRealChanging(value);
					this.SendPropertyChanging();
					this._FacConReal = value;
					this.SendPropertyChanged("FacConReal");
					this.OnFacConRealChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacTotPto", DbType="Money")]
		public System.Nullable<decimal> FacTotPto
		{
			get
			{
				return this._FacTotPto;
			}
			set
			{
				if ((this._FacTotPto != value))
				{
					this.OnFacTotPtoChanging(value);
					this.SendPropertyChanging();
					this._FacTotPto = value;
					this.SendPropertyChanged("FacTotPto");
					this.OnFacTotPtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacFecFac", DbType="DateTime")]
		public System.Nullable<System.DateTime> FacFecFac
		{
			get
			{
				return this._FacFecFac;
			}
			set
			{
				if ((this._FacFecFac != value))
				{
					this.OnFacFecFacChanging(value);
					this.SendPropertyChanging();
					this._FacFecFac = value;
					this.SendPropertyChanged("FacFecFac");
					this.OnFacFecFacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacHorFac", DbType="Char(8)")]
		public string FacHorFac
		{
			get
			{
				return this._FacHorFac;
			}
			set
			{
				if ((this._FacHorFac != value))
				{
					this.OnFacHorFacChanging(value);
					this.SendPropertyChanging();
					this._FacHorFac = value;
					this.SendPropertyChanged("FacHorFac");
					this.OnFacHorFacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CajaId", DbType="SmallInt")]
		public System.Nullable<short> CajaId
		{
			get
			{
				return this._CajaId;
			}
			set
			{
				if ((this._CajaId != value))
				{
					this.OnCajaIdChanging(value);
					this.SendPropertyChanging();
					this._CajaId = value;
					this.SendPropertyChanged("CajaId");
					this.OnCajaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacTipo", DbType="Char(1)")]
		public System.Nullable<char> FacTipo
		{
			get
			{
				return this._FacTipo;
			}
			set
			{
				if ((this._FacTipo != value))
				{
					this.OnFacTipoChanging(value);
					this.SendPropertyChanging();
					this._FacTipo = value;
					this.SendPropertyChanged("FacTipo");
					this.OnFacTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacConTip", DbType="Char(1)")]
		public System.Nullable<char> FacConTip
		{
			get
			{
				return this._FacConTip;
			}
			set
			{
				if ((this._FacConTip != value))
				{
					this.OnFacConTipChanging(value);
					this.SendPropertyChanging();
					this._FacConTip = value;
					this.SendPropertyChanged("FacConTip");
					this.OnFacConTipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacAnulada", DbType="Char(1)")]
		public System.Nullable<char> FacAnulada
		{
			get
			{
				return this._FacAnulada;
			}
			set
			{
				if ((this._FacAnulada != value))
				{
					this.OnFacAnuladaChanging(value);
					this.SendPropertyChanging();
					this._FacAnulada = value;
					this.SendPropertyChanged("FacAnulada");
					this.OnFacAnuladaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCerrada", DbType="Char(1)")]
		public System.Nullable<char> FacCerrada
		{
			get
			{
				return this._FacCerrada;
			}
			set
			{
				if ((this._FacCerrada != value))
				{
					this.OnFacCerradaChanging(value);
					this.SendPropertyChanging();
					this._FacCerrada = value;
					this.SendPropertyChanged("FacCerrada");
					this.OnFacCerradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCierre", DbType="Int")]
		public System.Nullable<int> FacCierre
		{
			get
			{
				return this._FacCierre;
			}
			set
			{
				if ((this._FacCierre != value))
				{
					this.OnFacCierreChanging(value);
					this.SendPropertyChanging();
					this._FacCierre = value;
					this.SendPropertyChanged("FacCierre");
					this.OnFacCierreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacTipPag", DbType="Char(1)")]
		public System.Nullable<char> FacTipPag
		{
			get
			{
				return this._FacTipPag;
			}
			set
			{
				if ((this._FacTipPag != value))
				{
					this.OnFacTipPagChanging(value);
					this.SendPropertyChanging();
					this._FacTipPag = value;
					this.SendPropertyChanged("FacTipPag");
					this.OnFacTipPagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacEfectivo", DbType="Money")]
		public System.Nullable<decimal> FacEfectivo
		{
			get
			{
				return this._FacEfectivo;
			}
			set
			{
				if ((this._FacEfectivo != value))
				{
					this.OnFacEfectivoChanging(value);
					this.SendPropertyChanging();
					this._FacEfectivo = value;
					this.SendPropertyChanged("FacEfectivo");
					this.OnFacEfectivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCambio", DbType="Money")]
		public System.Nullable<decimal> FacCambio
		{
			get
			{
				return this._FacCambio;
			}
			set
			{
				if ((this._FacCambio != value))
				{
					this.OnFacCambioChanging(value);
					this.SendPropertyChanging();
					this._FacCambio = value;
					this.SendPropertyChanged("FacCambio");
					this.OnFacCambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacZCierre", DbType="Int")]
		public System.Nullable<int> FacZCierre
		{
			get
			{
				return this._FacZCierre;
			}
			set
			{
				if ((this._FacZCierre != value))
				{
					this.OnFacZCierreChanging(value);
					this.SendPropertyChanging();
					this._FacZCierre = value;
					this.SendPropertyChanged("FacZCierre");
					this.OnFacZCierreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacSerie", DbType="Char(1)")]
		public System.Nullable<char> FacSerie
		{
			get
			{
				return this._FacSerie;
			}
			set
			{
				if ((this._FacSerie != value))
				{
					this.OnFacSerieChanging(value);
					this.SendPropertyChanging();
					this._FacSerie = value;
					this.SendPropertyChanged("FacSerie");
					this.OnFacSerieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetCobId", DbType="Int")]
		public System.Nullable<int> DetCobId
		{
			get
			{
				return this._DetCobId;
			}
			set
			{
				if ((this._DetCobId != value))
				{
					this.OnDetCobIdChanging(value);
					this.SendPropertyChanging();
					this._DetCobId = value;
					this.SendPropertyChanged("DetCobId");
					this.OnDetCobIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacMoneda", DbType="SmallInt")]
		public System.Nullable<short> FacMoneda
		{
			get
			{
				return this._FacMoneda;
			}
			set
			{
				if ((this._FacMoneda != value))
				{
					this.OnFacMonedaChanging(value);
					this.SendPropertyChanging();
					this._FacMoneda = value;
					this.SendPropertyChanged("FacMoneda");
					this.OnFacMonedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacFecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> FacFecha
		{
			get
			{
				return this._FacFecha;
			}
			set
			{
				if ((this._FacFecha != value))
				{
					this.OnFacFechaChanging(value);
					this.SendPropertyChanging();
					this._FacFecha = value;
					this.SendPropertyChanged("FacFecha");
					this.OnFacFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPaxNom", DbType="Char(40)")]
		public string FacPaxNom
		{
			get
			{
				return this._FacPaxNom;
			}
			set
			{
				if ((this._FacPaxNom != value))
				{
					this.OnFacPaxNomChanging(value);
					this.SendPropertyChanging();
					this._FacPaxNom = value;
					this.SendPropertyChanged("FacPaxNom");
					this.OnFacPaxNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPaxRuc", DbType="Decimal(15,0)")]
		public System.Nullable<decimal> FacPaxRuc
		{
			get
			{
				return this._FacPaxRuc;
			}
			set
			{
				if ((this._FacPaxRuc != value))
				{
					this.OnFacPaxRucChanging(value);
					this.SendPropertyChanging();
					this._FacPaxRuc = value;
					this.SendPropertyChanged("FacPaxRuc");
					this.OnFacPaxRucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPaxDir", DbType="Char(40)")]
		public string FacPaxDir
		{
			get
			{
				return this._FacPaxDir;
			}
			set
			{
				if ((this._FacPaxDir != value))
				{
					this.OnFacPaxDirChanging(value);
					this.SendPropertyChanging();
					this._FacPaxDir = value;
					this.SendPropertyChanged("FacPaxDir");
					this.OnFacPaxDirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPaxHab", DbType="SmallInt")]
		public System.Nullable<short> FacPaxHab
		{
			get
			{
				return this._FacPaxHab;
			}
			set
			{
				if ((this._FacPaxHab != value))
				{
					this.OnFacPaxHabChanging(value);
					this.SendPropertyChanging();
					this._FacPaxHab = value;
					this.SendPropertyChanged("FacPaxHab");
					this.OnFacPaxHabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPaxRes", DbType="Int")]
		public System.Nullable<int> FacPaxRes
		{
			get
			{
				return this._FacPaxRes;
			}
			set
			{
				if ((this._FacPaxRes != value))
				{
					this.OnFacPaxResChanging(value);
					this.SendPropertyChanging();
					this._FacPaxRes = value;
					this.SendPropertyChanged("FacPaxRes");
					this.OnFacPaxResChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPaxFEnt", DbType="DateTime")]
		public System.Nullable<System.DateTime> FacPaxFEnt
		{
			get
			{
				return this._FacPaxFEnt;
			}
			set
			{
				if ((this._FacPaxFEnt != value))
				{
					this.OnFacPaxFEntChanging(value);
					this.SendPropertyChanging();
					this._FacPaxFEnt = value;
					this.SendPropertyChanged("FacPaxFEnt");
					this.OnFacPaxFEntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPaxHEnt", DbType="Char(8)")]
		public string FacPaxHEnt
		{
			get
			{
				return this._FacPaxHEnt;
			}
			set
			{
				if ((this._FacPaxHEnt != value))
				{
					this.OnFacPaxHEntChanging(value);
					this.SendPropertyChanging();
					this._FacPaxHEnt = value;
					this.SendPropertyChanged("FacPaxHEnt");
					this.OnFacPaxHEntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPaxFSal", DbType="DateTime")]
		public System.Nullable<System.DateTime> FacPaxFSal
		{
			get
			{
				return this._FacPaxFSal;
			}
			set
			{
				if ((this._FacPaxFSal != value))
				{
					this.OnFacPaxFSalChanging(value);
					this.SendPropertyChanging();
					this._FacPaxFSal = value;
					this.SendPropertyChanged("FacPaxFSal");
					this.OnFacPaxFSalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPaxHSal", DbType="Char(8)")]
		public string FacPaxHSal
		{
			get
			{
				return this._FacPaxHSal;
			}
			set
			{
				if ((this._FacPaxHSal != value))
				{
					this.OnFacPaxHSalChanging(value);
					this.SendPropertyChanging();
					this._FacPaxHSal = value;
					this.SendPropertyChanged("FacPaxHSal");
					this.OnFacPaxHSalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacFecAnul", DbType="DateTime")]
		public System.Nullable<System.DateTime> FacFecAnul
		{
			get
			{
				return this._FacFecAnul;
			}
			set
			{
				if ((this._FacFecAnul != value))
				{
					this.OnFacFecAnulChanging(value);
					this.SendPropertyChanging();
					this._FacFecAnul = value;
					this.SendPropertyChanged("FacFecAnul");
					this.OnFacFecAnulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacHorAnul", DbType="Char(8)")]
		public string FacHorAnul
		{
			get
			{
				return this._FacHorAnul;
			}
			set
			{
				if ((this._FacHorAnul != value))
				{
					this.OnFacHorAnulChanging(value);
					this.SendPropertyChanging();
					this._FacHorAnul = value;
					this.SendPropertyChanged("FacHorAnul");
					this.OnFacHorAnulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacUsuAnul", DbType="Char(10)")]
		public string FacUsuAnul
		{
			get
			{
				return this._FacUsuAnul;
			}
			set
			{
				if ((this._FacUsuAnul != value))
				{
					this.OnFacUsuAnulChanging(value);
					this.SendPropertyChanging();
					this._FacUsuAnul = value;
					this.SendPropertyChanged("FacUsuAnul");
					this.OnFacUsuAnulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacMaqAnul", DbType="Char(10)")]
		public string FacMaqAnul
		{
			get
			{
				return this._FacMaqAnul;
			}
			set
			{
				if ((this._FacMaqAnul != value))
				{
					this.OnFacMaqAnulChanging(value);
					this.SendPropertyChanging();
					this._FacMaqAnul = value;
					this.SendPropertyChanged("FacMaqAnul");
					this.OnFacMaqAnulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacTotHosp", DbType="Money")]
		public System.Nullable<decimal> FacTotHosp
		{
			get
			{
				return this._FacTotHosp;
			}
			set
			{
				if ((this._FacTotHosp != value))
				{
					this.OnFacTotHospChanging(value);
					this.SendPropertyChanging();
					this._FacTotHosp = value;
					this.SendPropertyChanged("FacTotHosp");
					this.OnFacTotHospChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacTotExtras", DbType="Money")]
		public System.Nullable<decimal> FacTotExtras
		{
			get
			{
				return this._FacTotExtras;
			}
			set
			{
				if ((this._FacTotExtras != value))
				{
					this.OnFacTotExtrasChanging(value);
					this.SendPropertyChanging();
					this._FacTotExtras = value;
					this.SendPropertyChanged("FacTotExtras");
					this.OnFacTotExtrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacTotDescu", DbType="Money")]
		public System.Nullable<decimal> FacTotDescu
		{
			get
			{
				return this._FacTotDescu;
			}
			set
			{
				if ((this._FacTotDescu != value))
				{
					this.OnFacTotDescuChanging(value);
					this.SendPropertyChanging();
					this._FacTotDescu = value;
					this.SendPropertyChanged("FacTotDescu");
					this.OnFacTotDescuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacTotImpu", DbType="Money")]
		public System.Nullable<decimal> FacTotImpu
		{
			get
			{
				return this._FacTotImpu;
			}
			set
			{
				if ((this._FacTotImpu != value))
				{
					this.OnFacTotImpuChanging(value);
					this.SendPropertyChanging();
					this._FacTotImpu = value;
					this.SendPropertyChanged("FacTotImpu");
					this.OnFacTotImpuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacTotGen", DbType="Money")]
		public System.Nullable<decimal> FacTotGen
		{
			get
			{
				return this._FacTotGen;
			}
			set
			{
				if ((this._FacTotGen != value))
				{
					this.OnFacTotGenChanging(value);
					this.SendPropertyChanging();
					this._FacTotGen = value;
					this.SendPropertyChanged("FacTotGen");
					this.OnFacTotGenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacSenia", DbType="Money")]
		public System.Nullable<decimal> FacSenia
		{
			get
			{
				return this._FacSenia;
			}
			set
			{
				if ((this._FacSenia != value))
				{
					this.OnFacSeniaChanging(value);
					this.SendPropertyChanging();
					this._FacSenia = value;
					this.SendPropertyChanged("FacSenia");
					this.OnFacSeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacSucId", DbType="Char(3)")]
		public string FacSucId
		{
			get
			{
				return this._FacSucId;
			}
			set
			{
				if ((this._FacSucId != value))
				{
					this.OnFacSucIdChanging(value);
					this.SendPropertyChanging();
					this._FacSucId = value;
					this.SendPropertyChanged("FacSucId");
					this.OnFacSucIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacJuntoConTicket", DbType="Int")]
		public System.Nullable<int> FacJuntoConTicket
		{
			get
			{
				return this._FacJuntoConTicket;
			}
			set
			{
				if ((this._FacJuntoConTicket != value))
				{
					this.OnFacJuntoConTicketChanging(value);
					this.SendPropertyChanging();
					this._FacJuntoConTicket = value;
					this.SendPropertyChanged("FacJuntoConTicket");
					this.OnFacJuntoConTicketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacAsientoInterno", DbType="Int")]
		public System.Nullable<int> FacAsientoInterno
		{
			get
			{
				return this._FacAsientoInterno;
			}
			set
			{
				if ((this._FacAsientoInterno != value))
				{
					this.OnFacAsientoInternoChanging(value);
					this.SendPropertyChanging();
					this._FacAsientoInterno = value;
					this.SendPropertyChanged("FacAsientoInterno");
					this.OnFacAsientoInternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacImpRedondeo", DbType="Money")]
		public System.Nullable<decimal> FacImpRedondeo
		{
			get
			{
				return this._FacImpRedondeo;
			}
			set
			{
				if ((this._FacImpRedondeo != value))
				{
					this.OnFacImpRedondeoChanging(value);
					this.SendPropertyChanging();
					this._FacImpRedondeo = value;
					this.SendPropertyChanged("FacImpRedondeo");
					this.OnFacImpRedondeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacDescuento", DbType="SmallMoney")]
		public System.Nullable<decimal> FacDescuento
		{
			get
			{
				return this._FacDescuento;
			}
			set
			{
				if ((this._FacDescuento != value))
				{
					this.OnFacDescuentoChanging(value);
					this.SendPropertyChanging();
					this._FacDescuento = value;
					this.SendPropertyChanged("FacDescuento");
					this.OnFacDescuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacTipoContribuyente", DbType="Char(1)")]
		public System.Nullable<char> FacTipoContribuyente
		{
			get
			{
				return this._FacTipoContribuyente;
			}
			set
			{
				if ((this._FacTipoContribuyente != value))
				{
					this.OnFacTipoContribuyenteChanging(value);
					this.SendPropertyChanging();
					this._FacTipoContribuyente = value;
					this.SendPropertyChanged("FacTipoContribuyente");
					this.OnFacTipoContribuyenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EveCod", DbType="Char(8)")]
		public string EveCod
		{
			get
			{
				return this._EveCod;
			}
			set
			{
				if ((this._EveCod != value))
				{
					this.OnEveCodChanging(value);
					this.SendPropertyChanging();
					this._EveCod = value;
					this.SendPropertyChanged("EveCod");
					this.OnEveCodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacImpresora", DbType="SmallInt")]
		public System.Nullable<short> FacImpresora
		{
			get
			{
				return this._FacImpresora;
			}
			set
			{
				if ((this._FacImpresora != value))
				{
					this.OnFacImpresoraChanging(value);
					this.SendPropertyChanging();
					this._FacImpresora = value;
					this.SendPropertyChanged("FacImpresora");
					this.OnFacImpresoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacUtilSaldoPes", DbType="Int")]
		public System.Nullable<int> FacUtilSaldoPes
		{
			get
			{
				return this._FacUtilSaldoPes;
			}
			set
			{
				if ((this._FacUtilSaldoPes != value))
				{
					this.OnFacUtilSaldoPesChanging(value);
					this.SendPropertyChanging();
					this._FacUtilSaldoPes = value;
					this.SendPropertyChanged("FacUtilSaldoPes");
					this.OnFacUtilSaldoPesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacUtilSaldoDol", DbType="Int")]
		public System.Nullable<int> FacUtilSaldoDol
		{
			get
			{
				return this._FacUtilSaldoDol;
			}
			set
			{
				if ((this._FacUtilSaldoDol != value))
				{
					this.OnFacUtilSaldoDolChanging(value);
					this.SendPropertyChanging();
					this._FacUtilSaldoDol = value;
					this.SendPropertyChanged("FacUtilSaldoDol");
					this.OnFacUtilSaldoDolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCierreTesoreria", DbType="Int")]
		public System.Nullable<int> FacCierreTesoreria
		{
			get
			{
				return this._FacCierreTesoreria;
			}
			set
			{
				if ((this._FacCierreTesoreria != value))
				{
					this.OnFacCierreTesoreriaChanging(value);
					this.SendPropertyChanging();
					this._FacCierreTesoreria = value;
					this.SendPropertyChanged("FacCierreTesoreria");
					this.OnFacCierreTesoreriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacNCMotivo", DbType="Char(80)")]
		public string FacNCMotivo
		{
			get
			{
				return this._FacNCMotivo;
			}
			set
			{
				if ((this._FacNCMotivo != value))
				{
					this.OnFacNCMotivoChanging(value);
					this.SendPropertyChanging();
					this._FacNCMotivo = value;
					this.SendPropertyChanged("FacNCMotivo");
					this.OnFacNCMotivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacNCUsuId", DbType="Char(10)")]
		public string FacNCUsuId
		{
			get
			{
				return this._FacNCUsuId;
			}
			set
			{
				if ((this._FacNCUsuId != value))
				{
					this.OnFacNCUsuIdChanging(value);
					this.SendPropertyChanging();
					this._FacNCUsuId = value;
					this.SendPropertyChanged("FacNCUsuId");
					this.OnFacNCUsuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacNCAccion", DbType="Char(1)")]
		public System.Nullable<char> FacNCAccion
		{
			get
			{
				return this._FacNCAccion;
			}
			set
			{
				if ((this._FacNCAccion != value))
				{
					this.OnFacNCAccionChanging(value);
					this.SendPropertyChanging();
					this._FacNCAccion = value;
					this.SendPropertyChanged("FacNCAccion");
					this.OnFacNCAccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacNCDineroDevuelto", DbType="Money")]
		public System.Nullable<decimal> FacNCDineroDevuelto
		{
			get
			{
				return this._FacNCDineroDevuelto;
			}
			set
			{
				if ((this._FacNCDineroDevuelto != value))
				{
					this.OnFacNCDineroDevueltoChanging(value);
					this.SendPropertyChanging();
					this._FacNCDineroDevuelto = value;
					this.SendPropertyChanged("FacNCDineroDevuelto");
					this.OnFacNCDineroDevueltoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCierreMensual", DbType="Int")]
		public System.Nullable<int> FacCierreMensual
		{
			get
			{
				return this._FacCierreMensual;
			}
			set
			{
				if ((this._FacCierreMensual != value))
				{
					this.OnFacCierreMensualChanging(value);
					this.SendPropertyChanging();
					this._FacCierreMensual = value;
					this.SendPropertyChanged("FacCierreMensual");
					this.OnFacCierreMensualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacDtoHospedaje", DbType="SmallInt")]
		public System.Nullable<short> FacDtoHospedaje
		{
			get
			{
				return this._FacDtoHospedaje;
			}
			set
			{
				if ((this._FacDtoHospedaje != value))
				{
					this.OnFacDtoHospedajeChanging(value);
					this.SendPropertyChanging();
					this._FacDtoHospedaje = value;
					this.SendPropertyChanged("FacDtoHospedaje");
					this.OnFacDtoHospedajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacDtoExtras", DbType="SmallInt")]
		public System.Nullable<short> FacDtoExtras
		{
			get
			{
				return this._FacDtoExtras;
			}
			set
			{
				if ((this._FacDtoExtras != value))
				{
					this.OnFacDtoExtrasChanging(value);
					this.SendPropertyChanging();
					this._FacDtoExtras = value;
					this.SendPropertyChanged("FacDtoExtras");
					this.OnFacDtoExtrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacRif", DbType="Char(20)")]
		public string FacRif
		{
			get
			{
				return this._FacRif;
			}
			set
			{
				if ((this._FacRif != value))
				{
					this.OnFacRifChanging(value);
					this.SendPropertyChanging();
					this._FacRif = value;
					this.SendPropertyChanged("FacRif");
					this.OnFacRifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPapelNum", DbType="Char(10)")]
		public string FacPapelNum
		{
			get
			{
				return this._FacPapelNum;
			}
			set
			{
				if ((this._FacPapelNum != value))
				{
					this.OnFacPapelNumChanging(value);
					this.SendPropertyChanging();
					this._FacPapelNum = value;
					this.SendPropertyChanged("FacPapelNum");
					this.OnFacPapelNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCco", DbType="Char(10)")]
		public string FacCco
		{
			get
			{
				return this._FacCco;
			}
			set
			{
				if ((this._FacCco != value))
				{
					this.OnFacCcoChanging(value);
					this.SendPropertyChanging();
					this._FacCco = value;
					this.SendPropertyChanged("FacCco");
					this.OnFacCcoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacFacturaAfectada", DbType="Char(10)")]
		public string FacFacturaAfectada
		{
			get
			{
				return this._FacFacturaAfectada;
			}
			set
			{
				if ((this._FacFacturaAfectada != value))
				{
					this.OnFacFacturaAfectadaChanging(value);
					this.SendPropertyChanging();
					this._FacFacturaAfectada = value;
					this.SendPropertyChanged("FacFacturaAfectada");
					this.OnFacFacturaAfectadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacIdAfectada", DbType="Int")]
		public System.Nullable<int> FacIdAfectada
		{
			get
			{
				return this._FacIdAfectada;
			}
			set
			{
				if ((this._FacIdAfectada != value))
				{
					this.OnFacIdAfectadaChanging(value);
					this.SendPropertyChanging();
					this._FacIdAfectada = value;
					this.SendPropertyChanged("FacIdAfectada");
					this.OnFacIdAfectadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacZCierreIntegrada", DbType="Int")]
		public System.Nullable<int> FacZCierreIntegrada
		{
			get
			{
				return this._FacZCierreIntegrada;
			}
			set
			{
				if ((this._FacZCierreIntegrada != value))
				{
					this.OnFacZCierreIntegradaChanging(value);
					this.SendPropertyChanging();
					this._FacZCierreIntegrada = value;
					this.SendPropertyChanged("FacZCierreIntegrada");
					this.OnFacZCierreIntegradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacZCierreMensual", DbType="Int")]
		public System.Nullable<int> FacZCierreMensual
		{
			get
			{
				return this._FacZCierreMensual;
			}
			set
			{
				if ((this._FacZCierreMensual != value))
				{
					this.OnFacZCierreMensualChanging(value);
					this.SendPropertyChanging();
					this._FacZCierreMensual = value;
					this.SendPropertyChanged("FacZCierreMensual");
					this.OnFacZCierreMensualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacSeniaUtilizada", DbType="Money")]
		public System.Nullable<decimal> FacSeniaUtilizada
		{
			get
			{
				return this._FacSeniaUtilizada;
			}
			set
			{
				if ((this._FacSeniaUtilizada != value))
				{
					this.OnFacSeniaUtilizadaChanging(value);
					this.SendPropertyChanging();
					this._FacSeniaUtilizada = value;
					this.SendPropertyChanged("FacSeniaUtilizada");
					this.OnFacSeniaUtilizadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCodigoError", DbType="Char(15)")]
		public string FacCodigoError
		{
			get
			{
				return this._FacCodigoError;
			}
			set
			{
				if ((this._FacCodigoError != value))
				{
					this.OnFacCodigoErrorChanging(value);
					this.SendPropertyChanging();
					this._FacCodigoError = value;
					this.SendPropertyChanged("FacCodigoError");
					this.OnFacCodigoErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacFechaHoraParaAnul", DbType="DateTime")]
		public System.Nullable<System.DateTime> FacFechaHoraParaAnul
		{
			get
			{
				return this._FacFechaHoraParaAnul;
			}
			set
			{
				if ((this._FacFechaHoraParaAnul != value))
				{
					this.OnFacFechaHoraParaAnulChanging(value);
					this.SendPropertyChanging();
					this._FacFechaHoraParaAnul = value;
					this.SendPropertyChanged("FacFechaHoraParaAnul");
					this.OnFacFechaHoraParaAnulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCFEFirma", DbType="Char(30)")]
		public string FacCFEFirma
		{
			get
			{
				return this._FacCFEFirma;
			}
			set
			{
				if ((this._FacCFEFirma != value))
				{
					this.OnFacCFEFirmaChanging(value);
					this.SendPropertyChanging();
					this._FacCFEFirma = value;
					this.SendPropertyChanged("FacCFEFirma");
					this.OnFacCFEFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCFETipo", DbType="SmallInt")]
		public System.Nullable<short> FacCFETipo
		{
			get
			{
				return this._FacCFETipo;
			}
			set
			{
				if ((this._FacCFETipo != value))
				{
					this.OnFacCFETipoChanging(value);
					this.SendPropertyChanging();
					this._FacCFETipo = value;
					this.SendPropertyChanged("FacCFETipo");
					this.OnFacCFETipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCFESerie", DbType="Char(3)")]
		public string FacCFESerie
		{
			get
			{
				return this._FacCFESerie;
			}
			set
			{
				if ((this._FacCFESerie != value))
				{
					this.OnFacCFESerieChanging(value);
					this.SendPropertyChanging();
					this._FacCFESerie = value;
					this.SendPropertyChanged("FacCFESerie");
					this.OnFacCFESerieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCFENumero", DbType="Int")]
		public System.Nullable<int> FacCFENumero
		{
			get
			{
				return this._FacCFENumero;
			}
			set
			{
				if ((this._FacCFENumero != value))
				{
					this.OnFacCFENumeroChanging(value);
					this.SendPropertyChanging();
					this._FacCFENumero = value;
					this.SendPropertyChanged("FacCFENumero");
					this.OnFacCFENumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCFEFechaEmision", DbType="DateTime")]
		public System.Nullable<System.DateTime> FacCFEFechaEmision
		{
			get
			{
				return this._FacCFEFechaEmision;
			}
			set
			{
				if ((this._FacCFEFechaEmision != value))
				{
					this.OnFacCFEFechaEmisionChanging(value);
					this.SendPropertyChanging();
					this._FacCFEFechaEmision = value;
					this.SendPropertyChanged("FacCFEFechaEmision");
					this.OnFacCFEFechaEmisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCFEReceptorCiudad", DbType="Char(50)")]
		public string FacCFEReceptorCiudad
		{
			get
			{
				return this._FacCFEReceptorCiudad;
			}
			set
			{
				if ((this._FacCFEReceptorCiudad != value))
				{
					this.OnFacCFEReceptorCiudadChanging(value);
					this.SendPropertyChanging();
					this._FacCFEReceptorCiudad = value;
					this.SendPropertyChanged("FacCFEReceptorCiudad");
					this.OnFacCFEReceptorCiudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCFEReceptorDepartamento", DbType="Char(50)")]
		public string FacCFEReceptorDepartamento
		{
			get
			{
				return this._FacCFEReceptorDepartamento;
			}
			set
			{
				if ((this._FacCFEReceptorDepartamento != value))
				{
					this.OnFacCFEReceptorDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._FacCFEReceptorDepartamento = value;
					this.SendPropertyChanged("FacCFEReceptorDepartamento");
					this.OnFacCFEReceptorDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCFEReceptorTipoDocIdentidad", DbType="SmallInt")]
		public System.Nullable<short> FacCFEReceptorTipoDocIdentidad
		{
			get
			{
				return this._FacCFEReceptorTipoDocIdentidad;
			}
			set
			{
				if ((this._FacCFEReceptorTipoDocIdentidad != value))
				{
					this.OnFacCFEReceptorTipoDocIdentidadChanging(value);
					this.SendPropertyChanging();
					this._FacCFEReceptorTipoDocIdentidad = value;
					this.SendPropertyChanged("FacCFEReceptorTipoDocIdentidad");
					this.OnFacCFEReceptorTipoDocIdentidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCFEReceptorNroDocIdentidad", DbType="Char(15)")]
		public string FacCFEReceptorNroDocIdentidad
		{
			get
			{
				return this._FacCFEReceptorNroDocIdentidad;
			}
			set
			{
				if ((this._FacCFEReceptorNroDocIdentidad != value))
				{
					this.OnFacCFEReceptorNroDocIdentidadChanging(value);
					this.SendPropertyChanging();
					this._FacCFEReceptorNroDocIdentidad = value;
					this.SendPropertyChanged("FacCFEReceptorNroDocIdentidad");
					this.OnFacCFEReceptorNroDocIdentidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCFECae", DbType="Char(30)")]
		public string FacCFECae
		{
			get
			{
				return this._FacCFECae;
			}
			set
			{
				if ((this._FacCFECae != value))
				{
					this.OnFacCFECaeChanging(value);
					this.SendPropertyChanging();
					this._FacCFECae = value;
					this.SendPropertyChanged("FacCFECae");
					this.OnFacCFECaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCFECaeVen", DbType="DateTime")]
		public System.Nullable<System.DateTime> FacCFECaeVen
		{
			get
			{
				return this._FacCFECaeVen;
			}
			set
			{
				if ((this._FacCFECaeVen != value))
				{
					this.OnFacCFECaeVenChanging(value);
					this.SendPropertyChanging();
					this._FacCFECaeVen = value;
					this.SendPropertyChanged("FacCFECaeVen");
					this.OnFacCFECaeVenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacAnuladaElectronica", DbType="Char(1)")]
		public System.Nullable<char> FacAnuladaElectronica
		{
			get
			{
				return this._FacAnuladaElectronica;
			}
			set
			{
				if ((this._FacAnuladaElectronica != value))
				{
					this.OnFacAnuladaElectronicaChanging(value);
					this.SendPropertyChanging();
					this._FacAnuladaElectronica = value;
					this.SendPropertyChanged("FacAnuladaElectronica");
					this.OnFacAnuladaElectronicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCFEReceptorPaisDGI", DbType="Char(2)")]
		public string FacCFEReceptorPaisDGI
		{
			get
			{
				return this._FacCFEReceptorPaisDGI;
			}
			set
			{
				if ((this._FacCFEReceptorPaisDGI != value))
				{
					this.OnFacCFEReceptorPaisDGIChanging(value);
					this.SendPropertyChanging();
					this._FacCFEReceptorPaisDGI = value;
					this.SendPropertyChanged("FacCFEReceptorPaisDGI");
					this.OnFacCFEReceptorPaisDGIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPaisCod", DbType="Char(3)")]
		public string FacPaisCod
		{
			get
			{
				return this._FacPaisCod;
			}
			set
			{
				if ((this._FacPaisCod != value))
				{
					this.OnFacPaisCodChanging(value);
					this.SendPropertyChanging();
					this._FacPaisCod = value;
					this.SendPropertyChanged("FacPaisCod");
					this.OnFacPaisCodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacContingencia", DbType="Char(1)")]
		public System.Nullable<char> FacContingencia
		{
			get
			{
				return this._FacContingencia;
			}
			set
			{
				if ((this._FacContingencia != value))
				{
					this.OnFacContingenciaChanging(value);
					this.SendPropertyChanging();
					this._FacContingencia = value;
					this.SendPropertyChanged("FacContingencia");
					this.OnFacContingenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacContingenciaFacCFECae", DbType="Char(30)")]
		public string FacContingenciaFacCFECae
		{
			get
			{
				return this._FacContingenciaFacCFECae;
			}
			set
			{
				if ((this._FacContingenciaFacCFECae != value))
				{
					this.OnFacContingenciaFacCFECaeChanging(value);
					this.SendPropertyChanging();
					this._FacContingenciaFacCFECae = value;
					this.SendPropertyChanged("FacContingenciaFacCFECae");
					this.OnFacContingenciaFacCFECaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacContingenciaFacCFESerie", DbType="Char(3)")]
		public string FacContingenciaFacCFESerie
		{
			get
			{
				return this._FacContingenciaFacCFESerie;
			}
			set
			{
				if ((this._FacContingenciaFacCFESerie != value))
				{
					this.OnFacContingenciaFacCFESerieChanging(value);
					this.SendPropertyChanging();
					this._FacContingenciaFacCFESerie = value;
					this.SendPropertyChanged("FacContingenciaFacCFESerie");
					this.OnFacContingenciaFacCFESerieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacContingenciaFacCFECaeVen", DbType="DateTime")]
		public System.Nullable<System.DateTime> FacContingenciaFacCFECaeVen
		{
			get
			{
				return this._FacContingenciaFacCFECaeVen;
			}
			set
			{
				if ((this._FacContingenciaFacCFECaeVen != value))
				{
					this.OnFacContingenciaFacCFECaeVenChanging(value);
					this.SendPropertyChanging();
					this._FacContingenciaFacCFECaeVen = value;
					this.SendPropertyChanged("FacContingenciaFacCFECaeVen");
					this.OnFacContingenciaFacCFECaeVenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacContingenciaCaeDesde", DbType="Int")]
		public System.Nullable<int> FacContingenciaCaeDesde
		{
			get
			{
				return this._FacContingenciaCaeDesde;
			}
			set
			{
				if ((this._FacContingenciaCaeDesde != value))
				{
					this.OnFacContingenciaCaeDesdeChanging(value);
					this.SendPropertyChanging();
					this._FacContingenciaCaeDesde = value;
					this.SendPropertyChanged("FacContingenciaCaeDesde");
					this.OnFacContingenciaCaeDesdeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacContingenciaCaeHasta", DbType="Int")]
		public System.Nullable<int> FacContingenciaCaeHasta
		{
			get
			{
				return this._FacContingenciaCaeHasta;
			}
			set
			{
				if ((this._FacContingenciaCaeHasta != value))
				{
					this.OnFacContingenciaCaeHastaChanging(value);
					this.SendPropertyChanging();
					this._FacContingenciaCaeHasta = value;
					this.SendPropertyChanged("FacContingenciaCaeHasta");
					this.OnFacContingenciaCaeHastaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacContingeciaCaeNumero", DbType="Int")]
		public System.Nullable<int> FacContingeciaCaeNumero
		{
			get
			{
				return this._FacContingeciaCaeNumero;
			}
			set
			{
				if ((this._FacContingeciaCaeNumero != value))
				{
					this.OnFacContingeciaCaeNumeroChanging(value);
					this.SendPropertyChanging();
					this._FacContingeciaCaeNumero = value;
					this.SendPropertyChanged("FacContingeciaCaeNumero");
					this.OnFacContingeciaCaeNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacSecuencialShoppping", DbType="Int")]
		public System.Nullable<int> FacSecuencialShoppping
		{
			get
			{
				return this._FacSecuencialShoppping;
			}
			set
			{
				if ((this._FacSecuencialShoppping != value))
				{
					this.OnFacSecuencialShopppingChanging(value);
					this.SendPropertyChanging();
					this._FacSecuencialShoppping = value;
					this.SendPropertyChanged("FacSecuencialShoppping");
					this.OnFacSecuencialShopppingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCliSucId", DbType="SmallInt")]
		public System.Nullable<short> FacCliSucId
		{
			get
			{
				return this._FacCliSucId;
			}
			set
			{
				if ((this._FacCliSucId != value))
				{
					this.OnFacCliSucIdChanging(value);
					this.SendPropertyChanging();
					this._FacCliSucId = value;
					this.SendPropertyChanged("FacCliSucId");
					this.OnFacCliSucIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCliSucurLey15921", DbType="Char(1)")]
		public System.Nullable<char> FacCliSucurLey15921
		{
			get
			{
				return this._FacCliSucurLey15921;
			}
			set
			{
				if ((this._FacCliSucurLey15921 != value))
				{
					this.OnFacCliSucurLey15921Changing(value);
					this.SendPropertyChanging();
					this._FacCliSucurLey15921 = value;
					this.SendPropertyChanged("FacCliSucurLey15921");
					this.OnFacCliSucurLey15921Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLisId", DbType="SmallInt")]
		public System.Nullable<short> FacLisId
		{
			get
			{
				return this._FacLisId;
			}
			set
			{
				if ((this._FacLisId != value))
				{
					this.OnFacLisIdChanging(value);
					this.SendPropertyChanging();
					this._FacLisId = value;
					this.SendPropertyChanged("FacLisId");
					this.OnFacLisIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCabExportacionId", DbType="Int")]
		public System.Nullable<int> FacCabExportacionId
		{
			get
			{
				return this._FacCabExportacionId;
			}
			set
			{
				if ((this._FacCabExportacionId != value))
				{
					this.OnFacCabExportacionIdChanging(value);
					this.SendPropertyChanging();
					this._FacCabExportacionId = value;
					this.SendPropertyChanged("FacCabExportacionId");
					this.OnFacCabExportacionIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FACTURA1")]
	public partial class FACTURA1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FacId;
		
		private short _FacLin;
		
		private string _FacDscCon;
		
		private string _FacPtoV;
		
		private System.Nullable<System.DateTime> _FacLinFec;
		
		private System.Nullable<decimal> _FacPreUnit;
		
		private System.Nullable<decimal> _FacLinCan;
		
		private System.Nullable<short> _FacCodDto;
		
		private System.Nullable<decimal> _FacDescuen;
		
		private System.Nullable<decimal> _FacLinDto;
		
		private System.Nullable<decimal> _FacTotLin;
		
		private System.Nullable<decimal> _FacLinCImp;
		
		private System.Nullable<int> _ArtId;
		
		private System.Nullable<decimal> _FacCant;
		
		private System.Nullable<decimal> _FacMonCosto;
		
		private System.Nullable<decimal> _FacPreCosto;
		
		private string _FacLinObs;
		
		private System.Nullable<short> _FacVenId;
		
		private System.Nullable<decimal> _FacComVend;
		
		private string _FacObsComis;
		
		private System.Nullable<short> _FacLinCostoMonId;
		
		private System.Nullable<decimal> _FacLinCosto;
		
		private string _FacLinObsDescuento;
		
		private System.Nullable<short> _FacLinEstConsumo;
		
		private System.Nullable<int> _FacLinExportacionId;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFacIdChanging(int value);
    partial void OnFacIdChanged();
    partial void OnFacLinChanging(short value);
    partial void OnFacLinChanged();
    partial void OnFacDscConChanging(string value);
    partial void OnFacDscConChanged();
    partial void OnFacPtoVChanging(string value);
    partial void OnFacPtoVChanged();
    partial void OnFacLinFecChanging(System.Nullable<System.DateTime> value);
    partial void OnFacLinFecChanged();
    partial void OnFacPreUnitChanging(System.Nullable<decimal> value);
    partial void OnFacPreUnitChanged();
    partial void OnFacLinCanChanging(System.Nullable<decimal> value);
    partial void OnFacLinCanChanged();
    partial void OnFacCodDtoChanging(System.Nullable<short> value);
    partial void OnFacCodDtoChanged();
    partial void OnFacDescuenChanging(System.Nullable<decimal> value);
    partial void OnFacDescuenChanged();
    partial void OnFacLinDtoChanging(System.Nullable<decimal> value);
    partial void OnFacLinDtoChanged();
    partial void OnFacTotLinChanging(System.Nullable<decimal> value);
    partial void OnFacTotLinChanged();
    partial void OnFacLinCImpChanging(System.Nullable<decimal> value);
    partial void OnFacLinCImpChanged();
    partial void OnArtIdChanging(System.Nullable<int> value);
    partial void OnArtIdChanged();
    partial void OnFacCantChanging(System.Nullable<decimal> value);
    partial void OnFacCantChanged();
    partial void OnFacMonCostoChanging(System.Nullable<decimal> value);
    partial void OnFacMonCostoChanged();
    partial void OnFacPreCostoChanging(System.Nullable<decimal> value);
    partial void OnFacPreCostoChanged();
    partial void OnFacLinObsChanging(string value);
    partial void OnFacLinObsChanged();
    partial void OnFacVenIdChanging(System.Nullable<short> value);
    partial void OnFacVenIdChanged();
    partial void OnFacComVendChanging(System.Nullable<decimal> value);
    partial void OnFacComVendChanged();
    partial void OnFacObsComisChanging(string value);
    partial void OnFacObsComisChanged();
    partial void OnFacLinCostoMonIdChanging(System.Nullable<short> value);
    partial void OnFacLinCostoMonIdChanged();
    partial void OnFacLinCostoChanging(System.Nullable<decimal> value);
    partial void OnFacLinCostoChanged();
    partial void OnFacLinObsDescuentoChanging(string value);
    partial void OnFacLinObsDescuentoChanged();
    partial void OnFacLinEstConsumoChanging(System.Nullable<short> value);
    partial void OnFacLinEstConsumoChanged();
    partial void OnFacLinExportacionIdChanging(System.Nullable<int> value);
    partial void OnFacLinExportacionIdChanged();
    #endregion
		
		public FACTURA1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FacId
		{
			get
			{
				return this._FacId;
			}
			set
			{
				if ((this._FacId != value))
				{
					this.OnFacIdChanging(value);
					this.SendPropertyChanging();
					this._FacId = value;
					this.SendPropertyChanged("FacId");
					this.OnFacIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLin", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short FacLin
		{
			get
			{
				return this._FacLin;
			}
			set
			{
				if ((this._FacLin != value))
				{
					this.OnFacLinChanging(value);
					this.SendPropertyChanging();
					this._FacLin = value;
					this.SendPropertyChanged("FacLin");
					this.OnFacLinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacDscCon", DbType="Char(40)")]
		public string FacDscCon
		{
			get
			{
				return this._FacDscCon;
			}
			set
			{
				if ((this._FacDscCon != value))
				{
					this.OnFacDscConChanging(value);
					this.SendPropertyChanging();
					this._FacDscCon = value;
					this.SendPropertyChanged("FacDscCon");
					this.OnFacDscConChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPtoV", DbType="Char(3)")]
		public string FacPtoV
		{
			get
			{
				return this._FacPtoV;
			}
			set
			{
				if ((this._FacPtoV != value))
				{
					this.OnFacPtoVChanging(value);
					this.SendPropertyChanging();
					this._FacPtoV = value;
					this.SendPropertyChanged("FacPtoV");
					this.OnFacPtoVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinFec", DbType="DateTime")]
		public System.Nullable<System.DateTime> FacLinFec
		{
			get
			{
				return this._FacLinFec;
			}
			set
			{
				if ((this._FacLinFec != value))
				{
					this.OnFacLinFecChanging(value);
					this.SendPropertyChanging();
					this._FacLinFec = value;
					this.SendPropertyChanged("FacLinFec");
					this.OnFacLinFecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPreUnit", DbType="Money")]
		public System.Nullable<decimal> FacPreUnit
		{
			get
			{
				return this._FacPreUnit;
			}
			set
			{
				if ((this._FacPreUnit != value))
				{
					this.OnFacPreUnitChanging(value);
					this.SendPropertyChanging();
					this._FacPreUnit = value;
					this.SendPropertyChanged("FacPreUnit");
					this.OnFacPreUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinCan", DbType="SmallMoney")]
		public System.Nullable<decimal> FacLinCan
		{
			get
			{
				return this._FacLinCan;
			}
			set
			{
				if ((this._FacLinCan != value))
				{
					this.OnFacLinCanChanging(value);
					this.SendPropertyChanging();
					this._FacLinCan = value;
					this.SendPropertyChanged("FacLinCan");
					this.OnFacLinCanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCodDto", DbType="SmallInt")]
		public System.Nullable<short> FacCodDto
		{
			get
			{
				return this._FacCodDto;
			}
			set
			{
				if ((this._FacCodDto != value))
				{
					this.OnFacCodDtoChanging(value);
					this.SendPropertyChanging();
					this._FacCodDto = value;
					this.SendPropertyChanged("FacCodDto");
					this.OnFacCodDtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacDescuen", DbType="SmallMoney")]
		public System.Nullable<decimal> FacDescuen
		{
			get
			{
				return this._FacDescuen;
			}
			set
			{
				if ((this._FacDescuen != value))
				{
					this.OnFacDescuenChanging(value);
					this.SendPropertyChanging();
					this._FacDescuen = value;
					this.SendPropertyChanged("FacDescuen");
					this.OnFacDescuenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinDto", DbType="Money")]
		public System.Nullable<decimal> FacLinDto
		{
			get
			{
				return this._FacLinDto;
			}
			set
			{
				if ((this._FacLinDto != value))
				{
					this.OnFacLinDtoChanging(value);
					this.SendPropertyChanging();
					this._FacLinDto = value;
					this.SendPropertyChanged("FacLinDto");
					this.OnFacLinDtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacTotLin", DbType="Money")]
		public System.Nullable<decimal> FacTotLin
		{
			get
			{
				return this._FacTotLin;
			}
			set
			{
				if ((this._FacTotLin != value))
				{
					this.OnFacTotLinChanging(value);
					this.SendPropertyChanging();
					this._FacTotLin = value;
					this.SendPropertyChanged("FacTotLin");
					this.OnFacTotLinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinCImp", DbType="Money")]
		public System.Nullable<decimal> FacLinCImp
		{
			get
			{
				return this._FacLinCImp;
			}
			set
			{
				if ((this._FacLinCImp != value))
				{
					this.OnFacLinCImpChanging(value);
					this.SendPropertyChanging();
					this._FacLinCImp = value;
					this.SendPropertyChanged("FacLinCImp");
					this.OnFacLinCImpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArtId", DbType="Int")]
		public System.Nullable<int> ArtId
		{
			get
			{
				return this._ArtId;
			}
			set
			{
				if ((this._ArtId != value))
				{
					this.OnArtIdChanging(value);
					this.SendPropertyChanging();
					this._ArtId = value;
					this.SendPropertyChanged("ArtId");
					this.OnArtIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacCant", DbType="SmallMoney")]
		public System.Nullable<decimal> FacCant
		{
			get
			{
				return this._FacCant;
			}
			set
			{
				if ((this._FacCant != value))
				{
					this.OnFacCantChanging(value);
					this.SendPropertyChanging();
					this._FacCant = value;
					this.SendPropertyChanged("FacCant");
					this.OnFacCantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacMonCosto", DbType="Money")]
		public System.Nullable<decimal> FacMonCosto
		{
			get
			{
				return this._FacMonCosto;
			}
			set
			{
				if ((this._FacMonCosto != value))
				{
					this.OnFacMonCostoChanging(value);
					this.SendPropertyChanging();
					this._FacMonCosto = value;
					this.SendPropertyChanged("FacMonCosto");
					this.OnFacMonCostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacPreCosto", DbType="Money")]
		public System.Nullable<decimal> FacPreCosto
		{
			get
			{
				return this._FacPreCosto;
			}
			set
			{
				if ((this._FacPreCosto != value))
				{
					this.OnFacPreCostoChanging(value);
					this.SendPropertyChanging();
					this._FacPreCosto = value;
					this.SendPropertyChanged("FacPreCosto");
					this.OnFacPreCostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinObs", DbType="Char(80)")]
		public string FacLinObs
		{
			get
			{
				return this._FacLinObs;
			}
			set
			{
				if ((this._FacLinObs != value))
				{
					this.OnFacLinObsChanging(value);
					this.SendPropertyChanging();
					this._FacLinObs = value;
					this.SendPropertyChanged("FacLinObs");
					this.OnFacLinObsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacVenId", DbType="SmallInt")]
		public System.Nullable<short> FacVenId
		{
			get
			{
				return this._FacVenId;
			}
			set
			{
				if ((this._FacVenId != value))
				{
					this.OnFacVenIdChanging(value);
					this.SendPropertyChanging();
					this._FacVenId = value;
					this.SendPropertyChanged("FacVenId");
					this.OnFacVenIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacComVend", DbType="Money")]
		public System.Nullable<decimal> FacComVend
		{
			get
			{
				return this._FacComVend;
			}
			set
			{
				if ((this._FacComVend != value))
				{
					this.OnFacComVendChanging(value);
					this.SendPropertyChanging();
					this._FacComVend = value;
					this.SendPropertyChanged("FacComVend");
					this.OnFacComVendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacObsComis", DbType="Char(150)")]
		public string FacObsComis
		{
			get
			{
				return this._FacObsComis;
			}
			set
			{
				if ((this._FacObsComis != value))
				{
					this.OnFacObsComisChanging(value);
					this.SendPropertyChanging();
					this._FacObsComis = value;
					this.SendPropertyChanged("FacObsComis");
					this.OnFacObsComisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinCostoMonId", DbType="SmallInt")]
		public System.Nullable<short> FacLinCostoMonId
		{
			get
			{
				return this._FacLinCostoMonId;
			}
			set
			{
				if ((this._FacLinCostoMonId != value))
				{
					this.OnFacLinCostoMonIdChanging(value);
					this.SendPropertyChanging();
					this._FacLinCostoMonId = value;
					this.SendPropertyChanged("FacLinCostoMonId");
					this.OnFacLinCostoMonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinCosto", DbType="Money")]
		public System.Nullable<decimal> FacLinCosto
		{
			get
			{
				return this._FacLinCosto;
			}
			set
			{
				if ((this._FacLinCosto != value))
				{
					this.OnFacLinCostoChanging(value);
					this.SendPropertyChanging();
					this._FacLinCosto = value;
					this.SendPropertyChanged("FacLinCosto");
					this.OnFacLinCostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinObsDescuento", DbType="Char(50)")]
		public string FacLinObsDescuento
		{
			get
			{
				return this._FacLinObsDescuento;
			}
			set
			{
				if ((this._FacLinObsDescuento != value))
				{
					this.OnFacLinObsDescuentoChanging(value);
					this.SendPropertyChanging();
					this._FacLinObsDescuento = value;
					this.SendPropertyChanged("FacLinObsDescuento");
					this.OnFacLinObsDescuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinEstConsumo", DbType="SmallInt")]
		public System.Nullable<short> FacLinEstConsumo
		{
			get
			{
				return this._FacLinEstConsumo;
			}
			set
			{
				if ((this._FacLinEstConsumo != value))
				{
					this.OnFacLinEstConsumoChanging(value);
					this.SendPropertyChanging();
					this._FacLinEstConsumo = value;
					this.SendPropertyChanged("FacLinEstConsumo");
					this.OnFacLinEstConsumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinExportacionId", DbType="Int")]
		public System.Nullable<int> FacLinExportacionId
		{
			get
			{
				return this._FacLinExportacionId;
			}
			set
			{
				if ((this._FacLinExportacionId != value))
				{
					this.OnFacLinExportacionIdChanging(value);
					this.SendPropertyChanging();
					this._FacLinExportacionId = value;
					this.SendPropertyChanged("FacLinExportacionId");
					this.OnFacLinExportacionIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FACTURALINIMPUESTO")]
	public partial class FACTURALINIMPUESTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FacId;
		
		private short _FacLin;
		
		private short _FacLinImpuestoIvaTip;
		
		private System.Nullable<decimal> _FacLinImporteImpuestoNeto;
		
		private System.Nullable<decimal> _FacLinImporteImpuestoIva;
		
		private System.Nullable<decimal> _FacLinImporteTotal;
		
		private System.Nullable<int> _FacLinImpExportacionId;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFacIdChanging(int value);
    partial void OnFacIdChanged();
    partial void OnFacLinChanging(short value);
    partial void OnFacLinChanged();
    partial void OnFacLinImpuestoIvaTipChanging(short value);
    partial void OnFacLinImpuestoIvaTipChanged();
    partial void OnFacLinImporteImpuestoNetoChanging(System.Nullable<decimal> value);
    partial void OnFacLinImporteImpuestoNetoChanged();
    partial void OnFacLinImporteImpuestoIvaChanging(System.Nullable<decimal> value);
    partial void OnFacLinImporteImpuestoIvaChanged();
    partial void OnFacLinImporteTotalChanging(System.Nullable<decimal> value);
    partial void OnFacLinImporteTotalChanged();
    partial void OnFacLinImpExportacionIdChanging(System.Nullable<int> value);
    partial void OnFacLinImpExportacionIdChanged();
    #endregion
		
		public FACTURALINIMPUESTO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FacId
		{
			get
			{
				return this._FacId;
			}
			set
			{
				if ((this._FacId != value))
				{
					this.OnFacIdChanging(value);
					this.SendPropertyChanging();
					this._FacId = value;
					this.SendPropertyChanged("FacId");
					this.OnFacIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLin", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short FacLin
		{
			get
			{
				return this._FacLin;
			}
			set
			{
				if ((this._FacLin != value))
				{
					this.OnFacLinChanging(value);
					this.SendPropertyChanging();
					this._FacLin = value;
					this.SendPropertyChanged("FacLin");
					this.OnFacLinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinImpuestoIvaTip", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short FacLinImpuestoIvaTip
		{
			get
			{
				return this._FacLinImpuestoIvaTip;
			}
			set
			{
				if ((this._FacLinImpuestoIvaTip != value))
				{
					this.OnFacLinImpuestoIvaTipChanging(value);
					this.SendPropertyChanging();
					this._FacLinImpuestoIvaTip = value;
					this.SendPropertyChanged("FacLinImpuestoIvaTip");
					this.OnFacLinImpuestoIvaTipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinImporteImpuestoNeto", DbType="Money")]
		public System.Nullable<decimal> FacLinImporteImpuestoNeto
		{
			get
			{
				return this._FacLinImporteImpuestoNeto;
			}
			set
			{
				if ((this._FacLinImporteImpuestoNeto != value))
				{
					this.OnFacLinImporteImpuestoNetoChanging(value);
					this.SendPropertyChanging();
					this._FacLinImporteImpuestoNeto = value;
					this.SendPropertyChanged("FacLinImporteImpuestoNeto");
					this.OnFacLinImporteImpuestoNetoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinImporteImpuestoIva", DbType="Money")]
		public System.Nullable<decimal> FacLinImporteImpuestoIva
		{
			get
			{
				return this._FacLinImporteImpuestoIva;
			}
			set
			{
				if ((this._FacLinImporteImpuestoIva != value))
				{
					this.OnFacLinImporteImpuestoIvaChanging(value);
					this.SendPropertyChanging();
					this._FacLinImporteImpuestoIva = value;
					this.SendPropertyChanged("FacLinImporteImpuestoIva");
					this.OnFacLinImporteImpuestoIvaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinImporteTotal", DbType="Money")]
		public System.Nullable<decimal> FacLinImporteTotal
		{
			get
			{
				return this._FacLinImporteTotal;
			}
			set
			{
				if ((this._FacLinImporteTotal != value))
				{
					this.OnFacLinImporteTotalChanging(value);
					this.SendPropertyChanging();
					this._FacLinImporteTotal = value;
					this.SendPropertyChanged("FacLinImporteTotal");
					this.OnFacLinImporteTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FacLinImpExportacionId", DbType="Int")]
		public System.Nullable<int> FacLinImpExportacionId
		{
			get
			{
				return this._FacLinImpExportacionId;
			}
			set
			{
				if ((this._FacLinImpExportacionId != value))
				{
					this.OnFacLinImpExportacionIdChanging(value);
					this.SendPropertyChanging();
					this._FacLinImpExportacionId = value;
					this.SendPropertyChanged("FacLinImpExportacionId");
					this.OnFacLinImpExportacionIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
